name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm@latest-10

      - uses: actions/checkout@v4

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
          ignore: archived brands images information issues
