name: Release plugin

on:
  push:
    tags:
      - "[0-9].[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install -g pnpm@latest-10
          pnpm install
          pnpm build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title="${{ github.ref_name }}" \
            ./dist/light-card-hue-feature.js
